import type { Kind } from './types'

export interface SeedItem {
  title: string
  originalTitle?: string
  year?: string
  creator?: string
  synopsis?: string
  totalEpisodes?: number
}

const movie: SeedItem[] = [
  { title: '霸王别姬', year: '1993', creator: '陈凯歌', synopsis: '一代名伶的悲欢离合，华语影史巅峰之作。' },
  { title: '肖申克的救赎', originalTitle: 'The Shawshank Redemption', year: '1994', creator: '弗兰克·德拉邦特', synopsis: '希望是好事，也许是世间最好的事。' },
  { title: '千与千寻', originalTitle: '千と千尋の神隠し', year: '2001', creator: '宫崎骏', synopsis: '误入神隐世界的少女成长记。' },
  { title: '泰坦尼克号', originalTitle: 'Titanic', year: '1997', creator: '詹姆斯·卡梅隆', synopsis: 'You jump, I jump. 永恒的爱情悲剧。' },
  { title: '这个杀手不太冷', originalTitle: 'Léon', year: '1994', creator: '吕克·贝松', synopsis: '杀手与少女互相救赎。' },
  { title: '阿甘正传', originalTitle: 'Forrest Gump', year: '1994', creator: '罗伯特·泽米吉斯', synopsis: '生活就像一盒巧克力。' },
  { title: '辛德勒的名单', originalTitle: "Schindler's List", year: '1993', creator: '史蒂文·斯皮尔伯格', synopsis: '救一命即救全世界。' },
  { title: '大话西游', year: '1995', creator: '刘镇伟', synopsis: '曾经有一份真挚的爱情摆在我面前……' },
  { title: '无间道', year: '2002', creator: '刘伟强 麦兆辉', synopsis: '对不起，我是警察。' },
  { title: '教父', originalTitle: 'The Godfather', year: '1972', creator: '弗朗西斯·福特·科波拉', synopsis: '我会给他一个无法拒绝的提议。' },
  { title: '盗梦空间', originalTitle: 'Inception', year: '2010', creator: '克里斯托弗·诺兰', synopsis: '梦境套梦境，陀螺还在转吗？' },
  { title: '星际穿越', originalTitle: 'Interstellar', year: '2014', creator: '克里斯托弗·诺兰', synopsis: '爱是穿越维度的引力。' },
  { title: '楚门的世界', originalTitle: 'The Truman Show', year: '1998', creator: '彼得·威尔', synopsis: '假如一切都是一场真人秀。' },
  { title: '活着', year: '1994', creator: '张艺谋', synopsis: '人生一世，草木一秋。' },
  { title: '花样年华', year: '2000', creator: '王家卫', synopsis: '如果多一张船票，你会不会跟我走？' },
  { title: '海上钢琴师', originalTitle: 'La leggenda del pianista', year: '1998', creator: '朱塞佩·托纳多雷', synopsis: '生于船，长于船，一生不下船。' },
  { title: '三傻大闹宝莱坞', originalTitle: '3 Idiots', year: '2009', creator: '拉库马·希拉尼', synopsis: '追求卓越，成功就会不期而至。' },
  { title: '寻梦环游记', originalTitle: 'Coco', year: '2017', creator: '李·昂克里奇', synopsis: '真正的死亡是世界上再没有一个人记得你。' },
  { title: '绿皮书', originalTitle: 'Green Book', year: '2018', creator: '彼得·法雷里', synopsis: '种族与偏见路上的一对旅伴。' },
  { title: '罗马假日', originalTitle: 'Roman Holiday', year: '1953', creator: '威廉·惠勒', synopsis: '公主与记者的罗马一日。' },
  { title: '末代皇帝', originalTitle: 'The Last Emperor', year: '1987', creator: '贝纳尔多·贝托鲁奇', synopsis: '紫禁城里最后一位皇帝的一生。' },
  { title: '当幸福来敲门', originalTitle: 'The Pursuit of Happyness', year: '2006', creator: '加布里埃莱·穆奇诺', synopsis: '别让人告诉你你成不了大器。' },
  { title: '超脱', originalTitle: 'Detachment', year: '2011', creator: '托尼·凯耶', synopsis: '教育的困境与个体的超脱。' },
]

const tv: SeedItem[] = [
  { title: '西游记', year: '1986', creator: '杨洁', synopsis: '敢问路在何方，六小龄童版经典。', totalEpisodes: 25 },
  { title: '红楼梦', year: '1987', creator: '王扶林', synopsis: '满纸荒唐言，一把辛酸泪。', totalEpisodes: 36 },
  { title: '三国演义', year: '1994', creator: '王扶林', synopsis: '滚滚长江东逝水。', totalEpisodes: 84 },
  { title: '水浒传', year: '1998', creator: '张绍林', synopsis: '梁山一百单八将。', totalEpisodes: 43 },
  { title: '琅琊榜', year: '2015', creator: '孔笙 李雪', synopsis: '江左梅郎，麒麟才子，得之可得天下。', totalEpisodes: 54 },
  { title: '甄嬛传', year: '2011', creator: '郑晓龙', synopsis: '后宫争斗剧的巅峰之作。', totalEpisodes: 76 },
  { title: '武林外传', year: '2006', creator: '尚敬', synopsis: '同福客栈的江湖喜剧。', totalEpisodes: 80 },
  { title: '大明王朝1566', year: '2007', creator: '张黎', synopsis: '帝王心术与社稷苍生。', totalEpisodes: 46 },
  { title: '亮剑', year: '2005', creator: '张前', synopsis: '逢敌必亮剑。', totalEpisodes: 30 },
  { title: '白夜追凶', year: '2017', creator: '王伟', synopsis: '双胞胎兄弟追凶疑云。', totalEpisodes: 32 },
  { title: '漫长的季节', year: '2023', creator: '辛爽', synopsis: '向前看，别回头。', totalEpisodes: 12 },
  { title: '权力的游戏', originalTitle: 'Game of Thrones', year: '2011', creator: '大卫·贝尼奥夫', synopsis: '凛冬将至。', totalEpisodes: 73 },
  { title: '绝命毒师', originalTitle: 'Breaking Bad', year: '2008', creator: '文斯·吉利根', synopsis: '化学老师变身毒枭。', totalEpisodes: 62 },
  { title: '老友记', originalTitle: 'Friends', year: '1994', creator: '大卫·克兰', synopsis: "I'll be there for you.", totalEpisodes: 236 },
  { title: '神探夏洛克', originalTitle: 'Sherlock', year: '2010', creator: '史蒂文·莫法特', synopsis: '福尔摩斯的现代演绎。', totalEpisodes: 13 },
  { title: '请回答1988', originalTitle: '응답하라 1988', year: '2015', creator: '申元浩', synopsis: '双门洞的温情岁月。', totalEpisodes: 20 },
]

const musical: SeedItem[] = [
  { title: '歌剧魅影', originalTitle: 'The Phantom of the Opera', year: '1986', creator: '安德鲁·劳埃德·韦伯', synopsis: '音乐剧史上的里程碑之作。' },
  { title: '悲惨世界', originalTitle: 'Les Misérables', year: '1985', creator: '克劳德-米歇尔·勋伯格', synopsis: '只要这世上还有愚昧与困苦，音乐就不会停。' },
  { title: '猫', originalTitle: 'Cats', year: '1981', creator: '安德鲁·劳埃德·韦伯', synopsis: '杰里科猫家族的午夜舞会。' },
  { title: '西贡小姐', originalTitle: 'Miss Saigon', year: '1989', creator: '克劳德-米歇尔·勋伯格', synopsis: '越战背景下的东方爱情悲剧。' },
  { title: '汉密尔顿', originalTitle: 'Hamilton', year: '2015', creator: '林-曼努尔·米兰达', synopsis: '用嘻哈音乐讲述美国开国元勋。' },
  { title: '芝加哥', originalTitle: 'Chicago', year: '1975', creator: '约翰·坎德尔', synopsis: '爵士时代的杀人案与媒体狂欢。' },
  { title: '妈妈咪呀！', originalTitle: 'Mamma Mia!', year: '1999', creator: '本尼·安德森', synopsis: 'ABBA 金曲串烧的浪漫喜剧。' },
  { title: '魔法坏女巫', originalTitle: 'Wicked', year: '2003', creator: '斯蒂芬·施瓦茨', synopsis: '绿野仙踪前传，恶女巫的另一面。' },
  { title: '狮子王', originalTitle: 'The Lion King', year: '1997', creator: '朱丽·泰莫', synopsis: '非洲草原的王者史诗。' },
  { title: '摇滚莫扎特', originalTitle: 'Mozart L’opéra Rock', year: '2009', creator: '杜·阿提斯', synopsis: '法式摇滚演绎天才音乐家。' },
  { title: '我，堂吉诃德', originalTitle: 'Man of La Mancha', year: '1965', creator: '米奇·利', synopsis: '追梦骑士的执念之歌。' },
  { title: '贝隆夫人', originalTitle: 'Evita', year: '1978', creator: '安德鲁·劳埃德·韦伯', synopsis: "阿根廷国母的一生，Don't Cry for Me Argentina。" },
  { title: '近乎正常', originalTitle: 'Next to Normal', year: '2008', creator: '汤姆·基特', synopsis: '关于躁郁症家庭的摇滚音乐剧。' },
  { title: '日落大道', originalTitle: 'Sunset Boulevard', year: '1993', creator: '安德鲁·劳埃德·韦伯', synopsis: '过气影星的痴狂与幻灭。' },
  { title: '六皇后', originalTitle: 'Six', year: '2017', creator: '托比·马洛 露西·莫斯', synopsis: '亨利八世的六位王后组团开唱，用流行金曲重新夺回自己的故事。' },
  { title: '马戏之王', originalTitle: 'The Greatest Showman', year: '2017', creator: '本吉·帕塞克 贾斯汀·保罗', synopsis: 'This Is Me，巴纳姆马戏团的燃情歌舞。' },
  { title: '巴黎圣母院', originalTitle: 'Notre-Dame de Paris', year: '1998', creator: '吕克·普拉蒙东', synopsis: '法式音乐剧经典，大教堂时代的爱与欲。' },
  { title: '罗密欧与朱丽叶', originalTitle: 'Roméo et Juliette', year: '2001', creator: '捷哈·普莱斯格维克', synopsis: '维罗纳城两大世仇之家的生死恋。' },
  { title: '十诫', originalTitle: 'Les Dix Commandements', year: '2000', creator: '帕斯卡尔·奥比斯波', synopsis: '法语音乐剧，摩西出埃及记的宏大史诗。' },
  { title: '太阳王', originalTitle: 'Le Roi Soleil', year: '2005', creator: '卡梅尔·瓦利', synopsis: '路易十四的黄金时代与爱情。' },
  { title: '小王子', originalTitle: 'Le Petit Prince', year: '2002', creator: '理查德·科西安特', synopsis: '法语音乐剧，献给所有仍是孩子的大人。' },
  { title: '红与黑', originalTitle: 'Le Rouge et le Noir', year: '2016', creator: '弗朗索瓦·舒凯', synopsis: '于连的野心与爱情，法式摇滚音乐剧。' },
  { title: '大鼻子情圣', originalTitle: 'Cyrano de Bergerac', year: '2019', creator: '文森特·尼科洛', synopsis: '丑鼻子下的深情，法式音乐剧。' },
  { title: '1789：巴士底狱的恋人', originalTitle: '1789: Les Amants de la Bastille', year: '2012', creator: '杜·阿提斯', synopsis: '法国大革命的爱情与革命之歌。' },
  { title: '三个火枪手', originalTitle: 'Les Trois Mousquetaires', year: '2016', creator: '杜·阿提斯', synopsis: '一人为全体，全体为一人！法式音乐剧。' },
  { title: '亚瑟王传奇', originalTitle: 'La Légende du Roi Arthur', year: '2015', creator: '杜·阿提斯', synopsis: '圆桌骑士与湖中仙女的故事。' },
  { title: '神曲', originalTitle: 'La Divina Commedia', year: '2007', creator: '马尔科·弗里西纳', synopsis: '意大利音乐剧，但丁的地狱、炼狱与天堂。' },
  { title: '罗密欧与朱丽叶：爱与恨', originalTitle: 'Giulietta e Romeo', year: '2013', creator: '里卡多·科钱特', synopsis: '意大利音乐剧版，维罗纳的宿命之恋。' },
  { title: '基督山伯爵', originalTitle: 'Il Conte di Montecristo', year: '2014', creator: '马尔科·弗里西纳', synopsis: '意大利音乐剧，复仇与宽恕的传奇。' },
]

const play: SeedItem[] = [
  { title: '雷雨', year: '1934', creator: '曹禺', synopsis: '中国现代话剧奠基之作。' },
  { title: '茶馆', year: '1957', creator: '老舍', synopsis: '一个大茶馆，就是一个小社会。' },
  { title: '日出', year: '1936', creator: '曹禺', synopsis: '陈白露的繁华与坠落。' },
  { title: '北京人', year: '1940', creator: '曹禺', synopsis: '没落的曾家，觉醒的时代。' },
  { title: '原野', year: '1937', creator: '曹禺', synopsis: '仇虎的复仇与挣扎。' },
  { title: '暗恋桃花源', year: '1986', creator: '赖声川', synopsis: '两个剧团共用一个舞台。' },
  { title: '如梦之梦', year: '2000', creator: '赖声川', synopsis: '一个故事里的故事，八小时剧场史诗。' },
  { title: '恋爱的犀牛', year: '1999', creator: '孟京辉', synopsis: '先锋话剧爱情经典。' },
  { title: '窝头会馆', year: '2009', creator: '刘恒', synopsis: '北京南城小人物的众生相。' },
  { title: '白鹿原', year: '2016', creator: '孟冰 改编', synopsis: '原上白鹿两家的恩怨。' },
  { title: '哈姆雷特', originalTitle: 'Hamlet', year: '1602', creator: '威廉·莎士比亚', synopsis: '生存还是毁灭，这是个问题。' },
  { title: '威尼斯商人', originalTitle: 'The Merchant of Venice', year: '1596', creator: '威廉·莎士比亚', synopsis: '一磅肉的契约与宽恕。' },
  { title: '等待戈多', originalTitle: 'Waiting for Godot', year: '1953', creator: '萨缪尔·贝克特', synopsis: '荒诞派戏剧的代表作。' },
  { title: '玩偶之家', originalTitle: 'A Doll’s House', year: '1879', creator: '易卜生', synopsis: '娜拉的出走。' },
]

const drama: SeedItem[] = [
  { title: '牡丹亭', year: '1598', creator: '汤显祖', synopsis: '昆曲之冠，情不知所起，一往而深。' },
  { title: '长生殿', year: '1688', creator: '洪昇', synopsis: '唐明皇与杨贵妃的爱情与江山。' },
  { title: '桃花扇', year: '1699', creator: '孔尚任', synopsis: '一把桃花扇，半部南明史。' },
  { title: '西厢记', year: '1295', creator: '王实甫', synopsis: '愿天下有情人终成眷属。' },
  { title: '霸王别姬（京剧）', year: '1922', creator: '梅兰芳', synopsis: '力拔山兮气盖世。' },
  { title: '贵妃醉酒', year: '1912', creator: '梅兰芳', synopsis: '京剧梅派代表剧目。' },
  { title: '锁麟囊', year: '1940', creator: '程砚秋', synopsis: '程派名剧，善有善报。' },
  { title: '窦娥冤', year: '1293', creator: '关汉卿', synopsis: '元杂剧巅峰，六月飞雪。' },
  { title: '赵氏孤儿', year: '1275', creator: '纪君祥', synopsis: '中国最早的复仇悲剧之一。' },
  { title: '图兰朵', originalTitle: 'Turandot', year: '1926', creator: '普契尼', synopsis: '今夜无人入眠。' },
  { title: '茶花女', originalTitle: 'La traviata', year: '1853', creator: '威尔第', synopsis: '歌剧史上的爱情悲剧经典。' },
  { title: '卡门', originalTitle: 'Carmen', year: '1875', creator: '比才', synopsis: '爱情像一只自由的鸟儿。' },
  { title: '费加罗的婚礼', originalTitle: 'Le nozze di Figaro', year: '1786', creator: '莫扎特', synopsis: '莫扎特的欢乐歌剧。' },
  { title: '尼伯龙根的指环', originalTitle: 'Der Ring des Nibelungen', year: '1876', creator: '瓦格纳', synopsis: '四联剧连演四晚的史诗歌剧。' },
  { title: '天鹅湖', originalTitle: 'Лебединое озеро', year: '1877', creator: '柴可夫斯基', synopsis: '芭蕾舞剧的代名词。' },
]

const novel: SeedItem[] = [
  { title: '红楼梦', year: '1791', creator: '曹雪芹', synopsis: '中国古典小说巅峰。' },
  { title: '三国演义', year: '1522', creator: '罗贯中', synopsis: '天下大势，分久必合，合久必分。' },
  { title: '西游记', year: '1592', creator: '吴承恩', synopsis: '九九八十一难。' },
  { title: '水浒传', year: '1589', creator: '施耐庵', synopsis: '官逼民反的群像史诗。' },
  { title: '百年孤独', originalTitle: 'Cien años de soledad', year: '1967', creator: '加西亚·马尔克斯', synopsis: '魔幻现实主义巅峰。' },
  { title: '平凡的世界', year: '1986', creator: '路遥', synopsis: '孙少平与孙少安的奋斗人生。' },
  { title: '活着', year: '1993', creator: '余华', synopsis: '人是为活着本身而活着的。' },
  { title: '围城', year: '1947', creator: '钱钟书', synopsis: '城外的人想进去，城里的人想出来。' },
  { title: '白鹿原', year: '1993', creator: '陈忠实', synopsis: '原上的乡土史诗。' },
  { title: '三体', year: '2008', creator: '刘慈欣', synopsis: '中国科幻里程碑，地球往事三部曲。', totalEpisodes: 3 },
  { title: '傲慢与偏见', originalTitle: 'Pride and Prejudice', year: '1813', creator: '简·奥斯汀', synopsis: '偏见让你无法接受我，傲慢让我无法爱你。' },
  { title: '战争与和平', originalTitle: 'Война и мир', year: '1869', creator: '托尔斯泰', synopsis: '俄国社会的恢弘史诗。' },
  { title: '月亮与六便士', originalTitle: 'The Moon and Sixpence', year: '1919', creator: '毛姆', synopsis: '满地都是六便士，他却抬头看见了月亮。' },
  { title: '老人与海', originalTitle: 'The Old Man and the Sea', year: '1952', creator: '海明威', synopsis: '人可以被毁灭，但不能被打败。' },
  { title: '小王子', originalTitle: 'Le Petit Prince', year: '1943', creator: '圣埃克苏佩里', synopsis: '所有大人最初都是孩子。' },
  { title: '1984', originalTitle: 'Nineteen Eighty-Four', year: '1949', creator: '乔治·奥威尔', synopsis: '老大哥在看着你。' },
  { title: '追风筝的人', originalTitle: 'The Kite Runner', year: '2003', creator: '卡勒德·胡赛尼', synopsis: '为你，千千万万遍。' },
  { title: '白夜行', originalTitle: '白夜行', year: '1999', creator: '东野圭吾', synopsis: '日本推理小说的无冕之王。' },
  { title: '盗墓笔记', year: '2006', creator: '南派三叔', synopsis: '半个铁三角，十年盗墓之旅。', totalEpisodes: 8 },
  { title: '鬼吹灯', year: '2006', creator: '天下霸唱', synopsis: '十六字阴阳风水秘术的探险传奇。', totalEpisodes: 8 },
  { title: '庆余年', year: '2007', creator: '猫腻', synopsis: '一朝醒来，庙堂与江湖间的权谋纵横。', totalEpisodes: 7 },
  { title: '诡秘之主', year: '2018', creator: '爱潜水的乌贼', synopsis: '蒸汽与机械的时代，愚者的登神之旅。', totalEpisodes: 8 },
  { title: '斗破苍穹', year: '2009', creator: '天蚕土豆', synopsis: '三十年河东，三十年河西，莫欺少年穷。', totalEpisodes: 5 },
  { title: '全职高手', year: '2011', creator: '蝴蝶蓝', synopsis: '荣耀，从来不是一个人的游戏。', totalEpisodes: 5 },
  { title: '斗罗大陆', year: '2008', creator: '唐家三少', synopsis: '穿越到斗罗世界的唐三成神之路。', totalEpisodes: 5 },
  { title: '凡人修仙传', year: '2008', creator: '忘语', synopsis: '凡人流修仙的开山之作。', totalEpisodes: 5 },
  { title: '雪中悍刀行', year: '2012', creator: '烽火戏诸侯', synopsis: '北凉世子徐凤年的江湖与庙堂。', totalEpisodes: 5 },
  { title: '龙族', year: '2009', creator: '江南', synopsis: '屠龙的少年终成恶龙？卡塞尔学院传奇。', totalEpisodes: 5 },
  { title: '诛仙', year: '2003', creator: '萧鼎', synopsis: '张小凡的青云问道。', totalEpisodes: 5 },
  { title: '琅琊榜', year: '2006', creator: '海宴', synopsis: '麒麟才子梅长苏的翻云覆雨。', totalEpisodes: 3 },
  { title: '天官赐福', year: '2017', creator: '墨香铜臭', synopsis: '谢怜与花城八百年的守护。', totalEpisodes: 5 },
]

const prose: SeedItem[] = [
  { title: '朝花夕拾', year: '1928', creator: '鲁迅', synopsis: '回忆性散文集，从百草园到三味书屋。' },
  { title: '背影', year: '1925', creator: '朱自清', synopsis: '我与父亲不相见已二年余了。' },
  { title: '荷塘月色', year: '1927', creator: '朱自清', synopsis: '月光如流水一般，静静地泻在这一片叶子和花上。' },
  { title: '我与地坛', year: '1991', creator: '史铁生', synopsis: '死是一件不必急于求成的事。' },
  { title: '人间草木', year: '1982', creator: '汪曾祺', synopsis: '一花一草皆有情味。' },
  { title: '文化苦旅', year: '1992', creator: '余秋雨', synopsis: '文明的苦旅，文化的叩问。' },
  { title: '雅舍小品', year: '1949', creator: '梁实秋', synopsis: '于日常琐碎中见人生趣味。' },
  { title: '湘行散记', year: '1936', creator: '沈从文', synopsis: '沅水之上的风土人情。' },
  { title: '写在人生边上', year: '1941', creator: '钱钟书', synopsis: '人生边上的一点哲学幽默。' },
  { title: '沉默的大多数', year: '1997', creator: '王小波', synopsis: '特立独行的思想随笔。' },
  { title: '瓦尔登湖', originalTitle: 'Walden', year: '1854', creator: '梭罗', synopsis: '湖畔两年，简朴生活的沉思。' },
  { title: '蒙田随笔', originalTitle: 'Essais', year: '1580', creator: '米歇尔·德·蒙田', synopsis: '现代随笔的鼻祖。' },
  { title: '培根随笔', originalTitle: 'Essays', year: '1597', creator: '弗兰西斯·培根', synopsis: '知识就是力量。' },
  { title: '给青年的十二封信', year: '1929', creator: '朱光潜', synopsis: '关于读书与人生的诚恳忠告。' },
]

const poetry: SeedItem[] = [
  { title: '诗经', year: '前1000', creator: '佚名', synopsis: '关关雎鸠，在河之洲。' },
  { title: '楚辞·离骚', year: '前300', creator: '屈原', synopsis: '路漫漫其修远兮，吾将上下而求索。' },
  { title: '唐诗三百首', year: '1763', creator: '蘅塘退士 编', synopsis: '熟读唐诗三百首，不会作诗也会吟。' },
  { title: '李白诗选', year: '760', creator: '李白', synopsis: '天生我材必有用，千金散尽还复来。' },
  { title: '杜甫诗选', year: '770', creator: '杜甫', synopsis: '安得广厦千万间，大庇天下寒士俱欢颜。' },
  { title: '苏轼词选', year: '1101', creator: '苏轼', synopsis: '大江东去，浪淘尽，千古风流人物。' },
  { title: '飞鸟集', originalTitle: 'Stray Birds', year: '1916', creator: '泰戈尔', synopsis: '生如夏花之绚烂，死如秋叶之静美。' },
  { title: '神曲', originalTitle: 'Divina Commedia', year: '1320', creator: '但丁', synopsis: '穿过地狱、炼狱，抵达天堂。' },
  { title: '草叶集', originalTitle: 'Leaves of Grass', year: '1855', creator: '惠特曼', synopsis: '我赞美我自己，歌唱我自己。' },
  { title: '海子的诗', year: '1995', creator: '海子', synopsis: '面朝大海，春暖花开。' },
  { title: '恶之花', originalTitle: 'Les Fleurs du mal', year: '1857', creator: '波德莱尔', synopsis: '现代主义诗歌的先声。' },
  { title: '莎士比亚十四行诗', originalTitle: 'Sonnets', year: '1609', creator: '莎士比亚', synopsis: 'Shall I compare thee to a summer’s day?' },
  { title: '吉檀迦利', originalTitle: 'Gitanjali', year: '1910', creator: '泰戈尔', synopsis: '献给神的颂歌，诺贝尔文学奖作品。' },
  { title: '北岛诗选', year: '1986', creator: '北岛', synopsis: '卑鄙是卑鄙者的通行证。' },
]

const anime: SeedItem[] = [
  { title: '千与千寻', originalTitle: '千と千尋の神隠し', year: '2001', creator: '宫崎骏', synopsis: '日本动画电影票房神话。', totalEpisodes: 1 },
  { title: '你的名字', originalTitle: '君の名は。', year: '2016', creator: '新海诚', synopsis: '跨越时空的相遇。', totalEpisodes: 1 },
  { title: '灌篮高手', originalTitle: 'スラムダンク', year: '1993', creator: '井上雄彦', synopsis: '称霸全国！青春的篮球。', totalEpisodes: 101 },
  { title: '海贼王', originalTitle: 'ONE PIECE', year: '1999', creator: '尾田荣一郎', synopsis: '我要成为海贼王！', totalEpisodes: 1000 },
  { title: '进击的巨人', originalTitle: '進撃の巨人', year: '2013', creator: '谏山创', synopsis: '献出你的心脏。', totalEpisodes: 88 },
  { title: '鬼灭之刃', originalTitle: '鬼滅の刃', year: '2019', creator: '吾峠呼世晴', synopsis: '炭治郎的斩鬼之旅。', totalEpisodes: 26 },
  { title: '新世纪福音战士', originalTitle: '新世紀エヴァンゲリオン', year: '1995', creator: '庵野秀明', synopsis: '御宅族动画的里程碑。', totalEpisodes: 26 },
  { title: '攻壳机动队', originalTitle: '攻殻機動隊', year: '1995', creator: '押井守', synopsis: '赛博朋克哲学之作。', totalEpisodes: 26 },
  { title: '钢之炼金术师', originalTitle: '鋼の錬金術師', year: '2003', creator: '荒川弘', synopsis: '等价交换的炼金术物语。', totalEpisodes: 51 },
  { title: '死亡笔记', originalTitle: 'DEATH NOTE', year: '2006', creator: '大场鸫', synopsis: '写在死亡笔记上的名字会死去。', totalEpisodes: 37 },
  { title: '命运石之门', originalTitle: 'STEINS;GATE', year: '2011', creator: '5pb.', synopsis: '世界线收束的科幻悬疑。', totalEpisodes: 24 },
  { title: '龙猫', originalTitle: 'となりのトトロ', year: '1988', creator: '宫崎骏', synopsis: '天真岁月的治愈童话。', totalEpisodes: 1 },
  { title: '天空之城', originalTitle: '天空の城ラピュタ', year: '1986', creator: '宫崎骏', synopsis: '希达与巴鲁的冒险。', totalEpisodes: 1 },
  { title: '灵笼', year: '2019', creator: '艺画开天', synopsis: '国产科幻动画的里程碑。', totalEpisodes: 16 },
  { title: '罗小黑战记', year: '2011', creator: 'MTJJ', synopsis: '国产治愈系动画代表。', totalEpisodes: 28 },
  { title: '葬送的芙莉莲', originalTitle: '葬送のフリーレン', year: '2023', creator: '山田钟人', synopsis: '勇者一行完结后的时间之诗。', totalEpisodes: 28 },
  { title: '火影忍者', originalTitle: 'NARUTO', year: '2002', creator: '岸本齐史', synopsis: '吊车尾鸣人的火影之路。', totalEpisodes: 720 },
  { title: '咒术回战', originalTitle: '呪術廻戦', year: '2020', creator: '芥见下下', synopsis: '诅咒与咒术师的战斗。', totalEpisodes: 47 },
  { title: '间谍过家家', originalTitle: 'SPY×FAMILY', year: '2022', creator: '远藤达哉', synopsis: '黄昏的伪装家庭喜剧。', totalEpisodes: 37 },
  { title: '孤独摇滚！', originalTitle: 'ぼっち・ざ・ろっく！', year: '2022', creator: '滨路晶', synopsis: '社恐吉他手的乐队梦。', totalEpisodes: 12 },
  { title: '排球少年', originalTitle: 'ハイキュー!!', year: '2014', creator: '古馆春一', synopsis: '飞翔吧，乌野高中排球队！', totalEpisodes: 85 },
  { title: '紫罗兰永恒花园', originalTitle: 'ヴァイオレット・エヴァーガーデン', year: '2018', creator: '晓佳奈', synopsis: '自动手记人偶代笔的信。', totalEpisodes: 13 },
  { title: '夏目友人帐', originalTitle: '夏目友人帳', year: '2008', creator: '绿川幸', synopsis: '看得见妖怪的少年与友人帐。', totalEpisodes: 13 },
]

export const SEED_CATALOG: Record<Kind, SeedItem[]> = {
  movie,
  tv,
  musical,
  play,
  drama,
  novel,
  prose,
  poetry,
  anime,
}
